stages:
  # - lint
  - test
  - build
  - deploy

variables:
  PYTHON_IMAGE: "python:3.12-slim"
  NODE_IMAGE: "node:20-slim"
  BACKEND_IMAGE: "$CI_REGISTRY_IMAGE/backend"
  FRONTEND_IMAGE: "$CI_REGISTRY_IMAGE/frontend"

.python-base:
  image: $PYTHON_IMAGE
  before_script:
    - pip install -r backend/requirements.txt
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/backend

.node-base:
  image: $NODE_IMAGE
  before_script:
    - cd frontend && npm ci

# lint-backend:
#   stage: lint
#   extends: .python-base
#   script:
#     - pip install ruff
#     - ruff check backend

# lint-frontend:
#   stage: lint
#   extends: .node-base
#   script:
#     - npm run lint

test-backend:
  stage: test
  extends: .python-base
  script:
    - pytest backend/tests

.docker-setup:
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  before_script:
    - until docker info; do sleep 1; done
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-backend:
  stage: build
  extends: .docker-setup
  script:
    - docker build --pull -t $BACKEND_IMAGE:latest -t $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA ./backend
    - docker push $BACKEND_IMAGE:latest
    - docker push $BACKEND_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
    - master

build-frontend:
  stage: build
  extends: .docker-setup
  script:
    - docker build --pull -t $FRONTEND_IMAGE:latest -t $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA ./frontend
    - docker push $FRONTEND_IMAGE:latest
    - docker push $FRONTEND_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main
    - master

.deploy-base:
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - '[[ -z "$SSH_PRIVATE_KEY" ]] && echo "SSH_PRIVATE_KEY is empty" && exit 1'
    - '[[ -z "$SERVER_IP" ]] && echo "SERVER_IP is empty" && exit 1'
    - '[[ -z "$SERVER_USER" ]] && echo "SERVER_USER is empty" && exit 1'
    - 'echo "$SSH_PRIVATE_KEY" | tr -d "\r" | ssh-add - > /dev/null'
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ ! -z "$SSH_KNOWN_HOSTS" ]] && echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts'
  only:
    - main
    - master
  environment:
    name: production

deploy-backend:
  stage: deploy
  extends: .deploy-base
  script:
    - |
      ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd ~/backend &&
        git pull &&
        # Останавливаем старую версию, если она есть
        [ -d "solution" ] && sudo docker compose -f solution/docker-compose.yml down || true
        cd backend &&
        echo 'DOCKER_IMAGE=$BACKEND_IMAGE' > .env &&
        echo 'TAG=$CI_COMMIT_SHORT_SHA' >> .env &&
        sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        sudo docker compose pull &&
        sudo docker compose up -d
      "

deploy-frontend:
  stage: deploy
  extends: .deploy-base
  script:
    - |
      ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd ~/backend &&
        git pull &&
        cd frontend &&
        echo 'DOCKER_IMAGE=$FRONTEND_IMAGE' > .env &&
        echo 'TAG=$CI_COMMIT_SHORT_SHA' >> .env &&
        sudo docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        sudo docker compose pull &&
        sudo docker compose up -d
      "